name: Electron CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: npm install
        run: |
          npm install
      - name: Publish
        run: |
          npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup artifacts Mac
        if: matrix.os == 'macOS-latest'
        run: |
          mkdir artifacts
          mv dist/*.dmg artifacts || true
          mv dist/*.zip artifacts || true
      - name: Cleanup artifacts Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          mv dist/*.exe artifacts
      - name: Cleanup artifacts Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir artifacts
          mv dist/*.snap artifacts || true
          mv dist/*.AppImage artifacts || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
